### ISSUE TITLE
Is it possiable to register the commands under global namespace, and not under a prefix?

### ISSUE THREAD

**Issue by rabin-io** [leinardi/ulauncher-systemctl#2]
I prefer just to type `reboot` and not `sys reboot`

**Comment by leinardi** [comment]
Sadly, afaik, it's not possible :( Please feel free to request that feature directly in the ulauncher issue tracker.

**Comment by rabin-io** [comment]
Got it, thx

https://github.com/Ulauncher/Ulauncher/issues/375

**Comment by rabin-io** [comment]
Got it, thx

https://github.com/Ulauncher/Ulauncher/issues/375

**Comment by rabin-io** [comment]
OK, seems like you can bypass this problem by creating a desktop file

    $ cat /usr/local/share/applications/suspend.desktop

```
[Desktop Entry]
Name=Suspend
Comment=Suspend
GenericName=Suspend
Exec=systemctl suspend -i
Icon=/usr/local/share/pixmaps/gnome_session_suspend.png
Type=Application
StartupNotify=true

```

thx
