### ISSUE TITLE
System Management Extension is not compatible with latest ULauncher version

### ISSUE THREAD

**Issue by papermache** [leinardi/ulauncher-systemctl#4]
Linux version: Linux 4.15.0-48-generic
ULauncher v5.3.0~beta1
Extension API v2.0.0

![image](https://user-images.githubusercontent.com/2126012/59810781-d70a2880-92d4-11e9-8eb5-04255c18e24d.png)

**Comment by endorama** [comment]
It seems a PR has been opened for this! #3

**Comment by leinardi** [comment]
Yes, thanks, I somehow missed the PR. I'm planning to review and test it this weekend.

**Comment by leinardi** [comment]
Done!

**Comment by papermache** [comment]
Thanks!
